'use strict'
const express = require('express')
const { createQuoteSchema, createExperience, editExperience, createProofOfPayment } = require('../../utils/schemas/quotes')
const validation = require('../../utils/middlewares/validationHandler')
const multerGuardar = require('../../utils/multer')
const quotesController = require('../../controllers/api/cotizacion')
const multerGuardarPDF = require('../../utils/multerPdf')
const authMiddleware = require('../../utils/middlewares/authMiddleware')
const decryptMiddleware = require('../../utils/middlewares/cipherMiddleware')

const router = express.Router()

router.get('/',  quotesController.getQuotesWithFilters)
router.get('/fecha/:id/:dias', authMiddleware, quotesController.getQuoteDateDays)
router.get('/comprobantes', authMiddleware, quotesController.getQuoteReceipts)
router.get('/pdf', authMiddleware, quotesController.getQuotePDF)
router.get('/:cotId', authMiddleware, quotesController.getQuoteById)
router.get('/productos/:cotId', authMiddleware, quotesController.getQuoteProducts)
router.post('/', /*authMiddleware,*/ /*validation(createQuoteSchema),*/ quotesController.createQuote)

router.post('/crearCotizacion', decryptMiddleware, authMiddleware, /*multerGuardarPDF.multerGuardarPDF('pdf'),*/ quotesController.createCotizacion)
router.put('/actualizaCotizacion', decryptMiddleware, authMiddleware, /*multerGuardarPDF.multerGuardarPDF('pdf'),*/ quotesController.updateCotizacion)
router.get('/getEmpresas/:emp', authMiddleware, quotesController.filterCompany)
router.get('/getCotizacion/:user', authMiddleware, quotesController.getCotizaciones)
router.get('/getProductos/:cotId', authMiddleware, quotesController.getCotizacionProductos)
router.get('/getBitacora/:cotId', authMiddleware, quotesController.getCotizacionLog)
router.get('/getUsuarios/:cotizacion',  quotesController.getQuoteBuyerAndSellerV2)



router.put('/update/:cotId', quotesController.createChildrenQuote)
router.get('/bitacora/:cotId', authMiddleware, quotesController.getQuoteLog)
router.get('/reportes/pagos/:reporte', authMiddleware, quotesController.getQuotePaymentReportByID)
router.post('/reportes/pagos', authMiddleware, quotesController.createQuotePaymentReportPayment)
router.put('/reportes/pagos', authMiddleware, quotesController.updateQuotePaymentReport)
router.delete('/reportes/pagos/:id', authMiddleware, quotesController.deleteQuotePaymentReportByID)
router.post('/reportes', authMiddleware, quotesController.createQuotePaymentReport)
router.put('/reportes', authMiddleware, quotesController.updateQuoteReport)
router.delete('/reportes', authMiddleware, quotesController.deleteQuoteReport)
router.post('/comentarios', quotesController.createQuoteComment)
router.delete('/comentarios', quotesController.deleteQuoteComments)
router.get('/reportes', authMiddleware, quotesController.getQuoteReports)
router.get('/reportes/:id', authMiddleware, quotesController.getQuoteReportByID)
router.put('/:cotId', authMiddleware, quotesController.updateQuoteStatus)
router.get('/comentarios/:id', authMiddleware, quotesController.getQuoteCommentsByID)
router.get('/comentarios/sin-leer/:id', authMiddleware, quotesController.getQuoteCommentsNotSeen)
router.put('/comentarios/sin-leer/:id', authMiddleware, quotesController.updateQuoteCommentsNotSeen)
router.post('/experiencias', authMiddleware, validation(createExperience), quotesController.createQuoteExperience)
router.put('/experiencias/:id', authMiddleware, validation(editExperience), quotesController.updateQuoteExperience)
router.get('/actualizacion/:id',  quotesController.getQuoteLatestUpdate)
router.get('/usuarios/:cotizacion',  quotesController.getQuoteBuyerAndSeller)
router.post('/comprobantes', authMiddleware, multerGuardar('imagen'), validation(createProofOfPayment), quotesController.createQuoteReceipt)
router.get('/por-pagar/:userID', authMiddleware, quotesController.getQuotesToRate)
router.get('/success/get', authMiddleware, quotesController.getSuccessCases)

module.exports = router
